# source: generated by Claude.ai
# run in rails bash shell with:
#       rails test test/controllers/health_controller_test.rb

require "test_helper"

class HealthControllerTest < ActionDispatch::IntegrationTest
  test "should get health check" do
    get '/health'
    assert_response :success
  end

  test "health check returns correct JSON structure" do
    get '/health'
    
    json_response = JSON.parse(response.body)
    
    assert_equal 'ok', json_response['status']
    assert_not_nil json_response['timestamp']
  end

  test "health check timestamp is in ISO 8601 format" do
    get '/health'
    
    json_response = JSON.parse(response.body)
    timestamp = json_response['timestamp']
    
    # Should be parseable as ISO 8601
    assert_nothing_raised do
      Time.iso8601(timestamp)
    end
  end

  test "health check does not require authentication" do
    # Even without any session or token, should work
    get '/health'
    assert_response :success
  end
end
