# source: generated by Claude.ai
# run in rails bash shell with:
#       rails test test/controllers/auth_controller_test.rb

# can also test manually with curl

require "test_helper"

class AuthControllerTest < ActionDispatch::IntegrationTest
  def setup
    @user = User.create!(
      username: "testuser",
      password: "password123"
    )
  end

  # Registration tests
  test "should register new user with valid credentials" do
    post '/auth/register', params: {
      username: "newuser",
      password: "password123"
    }, as: :json
    
    assert_response :created
    json_response = JSON.parse(response.body)
    
    assert_not_nil json_response['user']
    assert_not_nil json_response['token']
    assert_equal 'newuser', json_response['user']['username']
  end

  test "should not register user with invalid credentials" do
    post '/auth/register', params: {
      username: "ab",  # Too short
      password: "password123"
    }, as: :json
    
    assert_response :unprocessable_entity
    json_response = JSON.parse(response.body)
    
    assert_not_nil json_response['errors']
  end

  test "should not register user with duplicate username" do
    post '/auth/register', params: {
      username: "testuser",  # Already exists
      password: "password123"
    }, as: :json
    
    assert_response :unprocessable_entity
    json_response = JSON.parse(response.body)
    
    assert_includes json_response['errors'].join, 'taken'
  end

  test "registration should set session" do
    post '/auth/register', params: {
      username: "sessionuser",
      password: "password123"
    }, as: :json
    
    assert_not_nil session[:user_id]
  end

  # Login tests
  test "should login with valid credentials" do
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    assert_response :ok
    json_response = JSON.parse(response.body)
    
    assert_not_nil json_response['user']
    assert_not_nil json_response['token']
    assert_equal 'testuser', json_response['user']['username']
  end

  test "should not login with invalid password" do
    post '/auth/login', params: {
      username: "testuser",
      password: "wrongpassword"
    }, as: :json
    
    assert_response :unauthorized
    json_response = JSON.parse(response.body)
    
    assert_equal 'Invalid username or password', json_response['error']
  end

  test "should not login with invalid username" do
    post '/auth/login', params: {
      username: "nonexistent",
      password: "password123"
    }, as: :json
    
    assert_response :unauthorized
    json_response = JSON.parse(response.body)
    
    assert_equal 'Invalid username or password', json_response['error']
  end

  test "login should be case insensitive" do
    post '/auth/login', params: {
      username: "TESTUSER",  # Uppercase
      password: "password123"
    }, as: :json
    
    assert_response :ok
  end

  test "login should set session" do
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    assert_not_nil session[:user_id]
  end

  # Logout tests
  test "should logout successfully" do
    # Login first
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    # Then logout
    post '/auth/logout', as: :json
    
    assert_response :ok
    json_response = JSON.parse(response.body)
    
    assert_equal 'Logged out successfully', json_response['message']
    assert_nil session[:user_id]
  end

  # test "logout requires authentication" do # actually i don't think it does
  #   post '/auth/logout', as: :json
    
  #   assert_response :unauthorized
  # end

  # Refresh tests
  test "should refresh token with valid session" do
    # Login first
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    # Refresh token
    post '/auth/refresh', as: :json
    
    assert_response :ok
    json_response = JSON.parse(response.body)
    
    assert_not_nil json_response['user']
    assert_not_nil json_response['token']
  end

  # test "refresh should fail without session" do
  #   post '/auth/refresh', as: :json
    
  #   assert_response :unauthorized
  #   json_response = JSON.parse(response.body)
    
  #   assert_equal 'No session found', json_response['error']
  # end

  # Me endpoint tests
  test "should get current user info" do
    # Login first
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    # Get current user
    get '/auth/me', as: :json
    
    assert_response :ok
    json_response = JSON.parse(response.body)
    
    assert_equal 'testuser', json_response['username']
    assert_equal @user.id, json_response['id']
  end

  test "me endpoint should fail without authentication" do
    get '/auth/me', as: :json
    
    assert_response :unauthorized
  end

  # JWT token tests
  test "should authenticate with JWT token in header" do
    # Get token from login
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    token = JSON.parse(response.body)['token']
    
    # Clear session to test JWT-only auth
    reset!
    
    # Use token in Authorization header
    get '/auth/me', 
        headers: { 'Authorization': "Bearer #{token}" },
        as: :json
    
    assert_response :ok
  end

  test "should reject invalid JWT token" do
    get '/auth/me',
        headers: { 'Authorization': 'Bearer invalid_token' },
        as: :json
    
    assert_response :unauthorized
  end

  # Response format tests
  test "user response should include all required fields" do
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    json_response = JSON.parse(response.body)
    user_data = json_response['user']
    
    assert_not_nil user_data['id']
    assert_not_nil user_data['username']
    assert_not_nil user_data['created_at']
    assert_not_nil user_data['last_active_at']
  end

  test "timestamps should be in ISO 8601 format" do
    post '/auth/login', params: {
      username: "testuser",
      password: "password123"
    }, as: :json
    
    json_response = JSON.parse(response.body)
    created_at = json_response['user']['created_at']
    
    assert_nothing_raised do
      Time.iso8601(created_at)
    end
  end
end