# source: generated by Claude.ai
# run in rails bash shell with:
#       rails test test/models/expert_assignment_test.rb

# test/models/expert_assignment_test.rb
require "test_helper"

class ExpertAssignmentTest < ActiveSupport::TestCase
  def setup
    @initiator = User.create!(
      username: "initiator",
      password: "password123"
    )
    
    @expert = User.create!(
      username: "expert",
      password: "password123"
    )
    
    @conversation = Conversation.create!(
      title: "Test conversation",
      initiator: @initiator
    )
  end

  test "should create valid expert assignment" do
    assignment = ExpertAssignment.new(
      conversation: @conversation,
      expert: @expert
    )
    assert assignment.valid?
    assert assignment.save
  end

  test "should require conversation" do
    assignment = ExpertAssignment.new(expert: @expert)
    assert_not assignment.valid?
    assert_includes assignment.errors[:conversation], "must exist"
  end

  test "should require expert" do
    assignment = ExpertAssignment.new(conversation: @conversation)
    assert_not assignment.valid?
    assert_includes assignment.errors[:expert], "must exist"
  end

  test "should have default status of active" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    assert_equal "active", assignment.status
  end

  test "should automatically set assigned_at on create" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    assert_not_nil assignment.assigned_at
  end

  test "should allow valid status values" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    
    %w[active resolved].each do |status|
      assignment.status = status
      assert assignment.valid?, "#{status} should be a valid status"
    end
  end

  test "should not allow invalid status" do
    assignment = ExpertAssignment.new(
      conversation: @conversation,
      expert: @expert,
      status: "invalid"
    )
    assert_not assignment.valid?
    assert_includes assignment.errors[:status], "is not included in the list"
  end

  test "resolve! should update status and set resolved_at" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    
    assert_equal "active", assignment.status
    assert_nil assignment.resolved_at
    
    assignment.resolve!
    assignment.reload
    
    assert_equal "resolved", assignment.status
    assert_not_nil assignment.resolved_at
  end

  test "belongs to conversation" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    
    assert_equal @conversation, assignment.conversation
  end

  test "belongs to expert" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    
    assert_equal @expert, assignment.expert
  end

  test "destroying conversation destroys assignments" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    
    assignment_id = assignment.id
    @conversation.destroy
    
    assert_nil ExpertAssignment.find_by(id: assignment_id)
  end

  test "destroying expert destroys assignments" do
    assignment = ExpertAssignment.create!(
      conversation: @conversation,
      expert: @expert
    )
    
    assignment_id = assignment.id
    @expert.destroy
    
    assert_nil ExpertAssignment.find_by(id: assignment_id)
  end
end