# source: generated by Claude.ai
# run in rails bash shell with:
#       rails test test/models/expert_profile_test.rb

# test/models/expert_profile_test.rb
require "test_helper"

class ExpertProfileTest < ActiveSupport::TestCase
  def setup
    @user = User.create!(
      username: "expert_user",
      password: "password123"
    )
  end

  test "should create valid expert profile" do
    profile = ExpertProfile.new(
      user: @user,
      bio: "I'm an expert in Rails"
    )
    assert profile.valid?
    assert profile.save
  end

  test "should require user" do
    profile = ExpertProfile.new(bio: "Test bio")
    assert_not profile.valid?
    assert_includes profile.errors[:user], "must exist"
  end

  test "user_id must be unique" do
    ExpertProfile.create!(user: @user, bio: "First profile")
    
    duplicate = ExpertProfile.new(user: @user, bio: "Second profile")
    assert_not duplicate.valid?
    assert_includes duplicate.errors[:user_id], "has already been taken"
  end

  test "bio can be nil" do
    profile = ExpertProfile.new(user: @user)
    assert profile.valid?
  end

  test "knowledge_base_links can be nil and gets initialized to empty array" do
    profile = ExpertProfile.create!(user: @user)
    assert_equal [], profile.knowledge_base_links
  end

  test "can store knowledge_base_links as array" do
    profile = ExpertProfile.create!(
      user: @user,
      bio: "Expert",
      knowledge_base_links: ["https://example.com", "https://docs.example.com"]
    )
    
    profile.reload
    assert_equal ["https://example.com", "https://docs.example.com"], profile.knowledge_base_links
  end

  test "add_knowledge_base_link adds link to array" do
    profile = ExpertProfile.create!(user: @user)
    
    profile.add_knowledge_base_link("https://example.com")
    profile.reload
    
    assert_includes profile.knowledge_base_links, "https://example.com"
  end

  test "add_knowledge_base_link does not add duplicates" do
    profile = ExpertProfile.create!(user: @user)
    
    profile.add_knowledge_base_link("https://example.com")
    profile.add_knowledge_base_link("https://example.com")
    profile.reload
    
    assert_equal 1, profile.knowledge_base_links.count("https://example.com")
  end

  test "remove_knowledge_base_link removes link from array" do
    profile = ExpertProfile.create!(
      user: @user,
      knowledge_base_links: ["https://example.com", "https://other.com"]
    )
    
    profile.remove_knowledge_base_link("https://example.com")
    profile.reload
    
    assert_not_includes profile.knowledge_base_links, "https://example.com"
    assert_includes profile.knowledge_base_links, "https://other.com"
  end

  test "belongs to user" do
    profile = ExpertProfile.create!(user: @user)
    assert_equal @user, profile.user
  end

  test "destroying user destroys expert profile" do
    profile = ExpertProfile.create!(user: @user)
    profile_id = profile.id
    
    @user.destroy
    
    assert_nil ExpertProfile.find_by(id: profile_id)
  end
end