# source: generated by Claude.ai
# run in rails bash shell with:
#       rails test test/models/message_test.rb

require "test_helper"

class MessageTest < ActiveSupport::TestCase
  def setup
    @initiator = User.create!(
      username: "initiator",
      password: "password123"
    )
    
    @expert = User.create!(
      username: "expert",
      password: "password123"
    )
    
    @conversation = Conversation.create!(
      title: "Test conversation",
      initiator: @initiator
    )
  end

  test "should create valid message" do
    message = Message.new(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Hello, I need help"
    )
    assert message.valid?
    assert message.save
  end

  test "should require content" do
    message = Message.new(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator"
    )
    assert_not message.valid?
    assert_includes message.errors[:content], "can't be blank"
  end

  test "should require conversation" do
    message = Message.new(
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    assert_not message.valid?
    assert_includes message.errors[:conversation], "must exist"
  end

  test "should require sender" do
    message = Message.new(
      conversation: @conversation,
      sender_role: "initiator",
      content: "Test"
    )
    assert_not message.valid?
    assert_includes message.errors[:sender], "must exist"
  end

  test "should require sender_role" do
    message = Message.new(
      conversation: @conversation,
      sender: @initiator,
      content: "Test"
    )
    assert_not message.valid?
    assert_includes message.errors[:sender_role], "can't be blank"
  end

  test "should only allow valid sender_role values" do
    message = Message.new(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "invalid",
      content: "Test"
    )
    assert_not message.valid?
    assert_includes message.errors[:sender_role], "is not included in the list"
  end

  test "should allow initiator sender_role" do
    message = Message.new(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    assert message.valid?
  end

  test "should allow expert sender_role" do
    message = Message.new(
      conversation: @conversation,
      sender: @expert,
      sender_role: "expert",
      content: "Test"
    )
    assert message.valid?
  end

  test "should default is_read to false" do
    message = Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    assert_equal false, message.is_read
  end

  test "mark_as_read! should update is_read to true" do
    message = Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    
    assert_equal false, message.is_read
    
    message.mark_as_read!
    message.reload
    
    assert_equal true, message.is_read
  end

  test "belongs to conversation" do
    message = Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    
    assert_equal @conversation, message.conversation
  end

  test "belongs to sender" do
    message = Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    
    assert_equal @initiator, message.sender
  end

  test "creating message updates conversation last_message_at" do
    @conversation.update(last_message_at: nil)
    
    assert_nil @conversation.last_message_at
    
    Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test message"
    )
    
    @conversation.reload
    assert_not_nil @conversation.last_message_at
  end

  test "destroying conversation destroys messages" do
    message = Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    
    message_id = message.id
    @conversation.destroy
    
    assert_nil Message.find_by(id: message_id)
  end

  test "destroying sender destroys messages" do
    message = Message.create!(
      conversation: @conversation,
      sender: @initiator,
      sender_role: "initiator",
      content: "Test"
    )
    
    message_id = message.id
    @initiator.destroy
    
    assert_nil Message.find_by(id: message_id)
  end
end